@startuml password_gui.png

class NameLayout {
	}

NameLayout --> NameLabel
NameLayout --> NameInput
PasswordLayout --> PasswordLabel
PasswordLayout --> PasswordInput
MemoLayout --> MemoLabel
MemoLayout --> MemoInput

InputFormLayout --> NameLayout
InputFormLayout --> PasswordLayout
InputFormLayout --> MemoLayout

SelectComboLayout --> SelectComboLabel
SelectComboLayout --> SelectCombo

LefterLayout --> NewButton
LefterLayout --> SelectComboLayout
Lefterlayout --> DummyWidget

UpperLayout --> LefterLayout
UpperLayout --> InputFormLayout

ButtonLayout --> RegistButton
ButtonLayout --> DeleteButton

MainLayout --> UpperLayout
MainLayout --> ButtonLayout

PasswordUIWindow --> MainLayout
@enduml
